# Generated by Django 5.0.4 on 2025-04-19 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='city',
        ),
        migrations.RemoveField(
            model_name='station',
            name='quik_map',
        ),
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.CharField(choices=[('Thiruvanathapuram', 'Thiruvanathapuram'), ('Kollam', 'Kollam')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=False, max_length=15)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('Thiruvanathapuram', 'Thiruvanathapuram'), ('Kollam', 'Kollam')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.adminuser')),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.location'),
        ),
    ]
